### ISSUE TITLE
Local console admin dashboard

### ISSUE THREAD

**Issue by mariospas** [slicknode/slicknode#61]
First of all, this is an amazing project and I am very happy that it is open source. Thanks for that. 

I would like to use it with an on permise environment but I also want to use it from dev machines to access and manage my dgraph (graphql database). 

Is there any way that I can use console admin panel from my local machine? Can I host it in a docker image server ? 

Thanks again

**Comment by ivome** [comment]
@mariospas, sorry for the late response, that somehow got lost. You can absolutely use the admin console with an on-premise or local dev environment. In the console, just create a Self-Hosted project and then set the API-Endpoint to for example `http://localhost:3000` or an internal network. I hope that helps?

**Comment by mariospas** [comment]
@ivome I was able to access the graphiql ui under localhost:3000 but  when I use that command `slicknode console`, I am redirecting to https://console.slicknode.com/p/ and I cant use the console admin dashboard as my local slicknode instance is not exposed to public ip. Is there any way for me to access console admin dashboard locally ?

**Comment by ivome** [comment]
The admin dashboard itself is always hosted under `console.slicknode.com/p/you-project-name`, but if you set up a Self-Hosted project in the console you **can** use the admin dashboard with a local instance, as long as your browser can access the API (this can be localhost). This works because the hosted slicknode admin dashboard backend does not read data from your GraphQL API, only your browser does. You have to set the endpoint to your local address. Your browser will then make all the API calls to your endpoint directly.
